baseURL = "https://agntgalahad.github.io/"
languageCode = "en-us"
title = "Himanshu Patil"
theme="archie"
copyright = "© Himanshu"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "agntgalahad"


[params]
	mainSections = ["about"]
	mode="toggle" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support

# Social Tags
[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/himanshupatil829/"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/agntgalahad"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://x.com/agnt_galahad"


# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Projects"
url = "/projects"
weight = 2

[[menu.main]]
name = "Blogs"
url = "/blogs"
weight = 3

[[menu.main]]
name = "All Posts"
url = "/posts"
weight = 4

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 5
